# Generated by Django 5.1.4 on 2024-12-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_day_hour_space_room_review_amenity_spaceaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
