# Generated by Django 5.1.4 on 2024-12-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_roomimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
