# Generated by Django 5.1.4 on 2024-12-19 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_space_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='name',
            new_name='amenitie_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_name',
        ),
        migrations.AlterField(
            model_name='spaceaddress',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='spaces.province'),
        ),
    ]
