# Generated by Django 5.1.4 on 2024-12-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_delete_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomimage', to='spaces.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(related_name='images', to='spaces.roomimage'),
        ),
    ]
