# Generated by Django 5.1.4 on 2024-12-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_rename_name_amenity_amenitie_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='amenitie_name',
            new_name='amenity_name',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(related_name='rooms', to='spaces.amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
